// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Models;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817144117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyMvcApp.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("DiUng")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuKham", "MaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("ChiTietDichVus");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("CachDung")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("LieuDung")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuKham", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDonThuocs");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChuyenKhoa", b =>
                {
                    b.Property<int>("MaChuyenKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaChuyenKhoa"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaChuyenKhoa");

                    b.ToTable("ChuyenKhoas");
                });

            modelBuilder.Entity("MyMvcApp.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("MyMvcApp.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaNguoiLap")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuKham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TienThuoc")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaNguoiLap");

                    b.HasIndex("MaPhieuKham")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("MyMvcApp.Models.LichKham", b =>
                {
                    b.Property<int>("MaLichKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaLichKham"));

                    b.Property<TimeSpan>("GioKham")
                        .HasColumnType("time(6)");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaLichKham");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaBacSi", "NgayKham", "GioKham")
                        .IsUnique();

                    b.ToTable("LichKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("MaChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaChuyenKhoa");

                    b.HasIndex("SoDienThoai")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuKham", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaPhieuKham"));

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoiDan")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaLichKham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKham")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("MaPhieuKham");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaLichKham")
                        .IsUnique();

                    b.ToTable("PhieuKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MaThuoc"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuocs");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("MyMvcApp.Models.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.PhieuKham", "PhieuKham")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("MyMvcApp.Models.PhieuKham", "PhieuKham")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuKham");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("MyMvcApp.Models.HoaDon", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "NguoiLap")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNguoiLap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.PhieuKham", "PhieuKham")
                        .WithOne("HoaDon")
                        .HasForeignKey("MyMvcApp.Models.HoaDon", "MaPhieuKham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiLap");

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.LichKham", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "BacSi")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.BenhNhan", "BenhNhan")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("MyMvcApp.Models.NguoiDung", b =>
                {
                    b.HasOne("MyMvcApp.Models.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaChuyenKhoa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuKham", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "BacSi")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.BenhNhan", "BenhNhan")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.LichKham", "LichKham")
                        .WithOne("PhieuKham")
                        .HasForeignKey("MyMvcApp.Models.PhieuKham", "MaLichKham")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("LichKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.BenhNhan", b =>
                {
                    b.Navigation("LichKhams");

                    b.Navigation("PhieuKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("MyMvcApp.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("MyMvcApp.Models.LichKham", b =>
                {
                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.NguoiDung", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LichKhams");

                    b.Navigation("PhieuKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuKham", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("MyMvcApp.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
