// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Models;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260824041822_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyMvcApp.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiUng")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("CCCD")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL AND [CCCD] <> ''");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] <> ''");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("BenhNhans");

                    b.HasData(
                        new
                        {
                            MaBenhNhan = 1,
                            CCCD = "079090001111",
                            DiaChi = "Hà Nội",
                            Email = "bn.vip@gmail.com",
                            GioiTinh = "Nam",
                            HoTen = "Bệnh Nhân VIP",
                            MatKhau = "123456",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0811111111"
                        },
                        new
                        {
                            MaBenhNhan = 2,
                            CCCD = "079095002222",
                            DiUng = "Hải sản",
                            DiaChi = "TP.HCM",
                            Email = "bn.normal@gmail.com",
                            GioiTinh = "Nữ",
                            HoTen = "Bệnh Nhân Tiêu Chuẩn",
                            MatKhau = "123456",
                            NgaySinh = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0822222222"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuKham", "MaDichVu");

                    b.HasIndex("MaDichVu");

                    b.ToTable("ChiTietDichVus");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("CachDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("LieuDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuKham", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDonThuocs");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChuyenKhoa", b =>
                {
                    b.Property<int>("MaChuyenKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenKhoa"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuyenKhoa");

                    b.ToTable("ChuyenKhoas");

                    b.HasData(
                        new
                        {
                            MaChuyenKhoa = 1,
                            MoTa = "Chuyên khám và điều trị các bệnh nội khoa",
                            TenChuyenKhoa = "Khoa Nội"
                        },
                        new
                        {
                            MaChuyenKhoa = 2,
                            MoTa = "Chuyên phẫu thuật và điều trị các bệnh ngoại khoa",
                            TenChuyenKhoa = "Khoa Ngoại"
                        },
                        new
                        {
                            MaChuyenKhoa = 3,
                            MoTa = "Chuyên khám và điều trị bệnh cho trẻ em",
                            TenChuyenKhoa = "Nhi khoa"
                        },
                        new
                        {
                            MaChuyenKhoa = 4,
                            MoTa = "Chuyên khám và điều trị các bệnh phụ khoa, thai sản",
                            TenChuyenKhoa = "Sản phụ khoa"
                        },
                        new
                        {
                            MaChuyenKhoa = 5,
                            MoTa = "Chuyên khám và điều trị các bệnh răng hàm mặt",
                            TenChuyenKhoa = "Nha khoa"
                        },
                        new
                        {
                            MaChuyenKhoa = 6,
                            MoTa = "Chuyên khám và điều trị các bệnh về da",
                            TenChuyenKhoa = "Da liễu"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("MyMvcApp.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaNguoiLap")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuKham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TienThuoc")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TongTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaNguoiLap");

                    b.HasIndex("MaPhieuKham")
                        .IsUnique();

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("MyMvcApp.Models.LichKham", b =>
                {
                    b.Property<int>("MaLichKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichKham"));

                    b.Property<TimeSpan>("GioKham")
                        .HasColumnType("time");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichKham");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaBacSi", "NgayKham", "GioKham")
                        .IsUnique();

                    b.ToTable("LichKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaChuyenKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("MaChuyenKhoa");

                    b.HasIndex("SoDienThoai")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            Email = "admin@medicore.com",
                            HoTen = "Quản trị viên Hệ thống",
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Admin",
                            SoDienThoai = "0999999999",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            Email = "manager@medicore.com",
                            HoTen = "Giám đốc Điều hành",
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Manager",
                            SoDienThoai = "0988888888",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 3,
                            Email = "letan1@medicore.com",
                            HoTen = "Lễ Tân Số 1",
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "LeTan",
                            SoDienThoai = "0977777777",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 4,
                            Email = "letan2@medicore.com",
                            HoTen = "Lễ Tân Số 2",
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "LeTan",
                            SoDienThoai = "0966666666",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 5,
                            Email = "khoanm@medicore.com",
                            HoTen = "BS. Nguyễn Minh Khoa",
                            MaChuyenKhoa = 1,
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "BacSi",
                            SoDienThoai = "0911111111",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 6,
                            Email = "lanth@medicore.com",
                            HoTen = "ThS.BS. Trần Hữu Lan",
                            MaChuyenKhoa = 2,
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "BacSi",
                            SoDienThoai = "0922222222",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 7,
                            Email = "minhlq@medicore.com",
                            HoTen = "BS.CKII. Lê Quốc Minh",
                            MaChuyenKhoa = 3,
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "BacSi",
                            SoDienThoai = "0933333333",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 8,
                            Email = "phucph@medicore.com",
                            HoTen = "BS. Phạm Hoàng Phúc",
                            MaChuyenKhoa = 4,
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "BacSi",
                            SoDienThoai = "0944444444",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 9,
                            Email = "tuyetvt@medicore.com",
                            HoTen = "BS. Võ Thị Tuyết",
                            MaChuyenKhoa = 5,
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "BacSi",
                            SoDienThoai = "0955555555",
                            TrangThai = false
                        },
                        new
                        {
                            MaNguoiDung = 10,
                            Email = "thungan@medicore.com",
                            HoTen = "Thu Ngân 1",
                            MatKhau = "123456",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "ThuNgan",
                            SoDienThoai = "0900000000",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuChi", b =>
                {
                    b.Property<int>("MaPhieuChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuChi"));

                    b.Property<string>("LoaiPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiLap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("MaPhieuChi");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaNguoiLap");

                    b.ToTable("PhieuChis");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuKham", b =>
                {
                    b.Property<int>("MaPhieuKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuKham"));

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DanhGia")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoiDan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaLichKham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaPhieuKham");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaLichKham")
                        .IsUnique()
                        .HasFilter("[MaLichKham] IS NOT NULL");

                    b.ToTable("PhieuKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("MyMvcApp.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuocs");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("MyMvcApp.Models.DichVu", "DichVu")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.PhieuKham", "PhieuKham")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("MyMvcApp.Models.PhieuKham", "PhieuKham")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaPhieuKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuKham");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("MyMvcApp.Models.HoaDon", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "NguoiLap")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNguoiLap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.PhieuKham", "PhieuKham")
                        .WithOne("HoaDon")
                        .HasForeignKey("MyMvcApp.Models.HoaDon", "MaPhieuKham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiLap");

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.LichKham", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "BacSi")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.BenhNhan", "BenhNhan")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("MyMvcApp.Models.NguoiDung", b =>
                {
                    b.HasOne("MyMvcApp.Models.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaChuyenKhoa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuChi", b =>
                {
                    b.HasOne("MyMvcApp.Models.BenhNhan", "BenhNhan")
                        .WithMany()
                        .HasForeignKey("MaBenhNhan");

                    b.HasOne("MyMvcApp.Models.NguoiDung", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("MaNguoiLap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("NguoiLap");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuKham", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "BacSi")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.BenhNhan", "BenhNhan")
                        .WithMany("PhieuKhams")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.LichKham", "LichKham")
                        .WithOne("PhieuKham")
                        .HasForeignKey("MyMvcApp.Models.PhieuKham", "MaLichKham")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("LichKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.ThongBao", b =>
                {
                    b.HasOne("MyMvcApp.Models.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("MyMvcApp.Models.BenhNhan", b =>
                {
                    b.Navigation("LichKhams");

                    b.Navigation("PhieuKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.ChuyenKhoa", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("MyMvcApp.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("MyMvcApp.Models.LichKham", b =>
                {
                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("MyMvcApp.Models.NguoiDung", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LichKhams");

                    b.Navigation("PhieuKhams");
                });

            modelBuilder.Entity("MyMvcApp.Models.PhieuKham", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("ChiTietDonThuocs");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("MyMvcApp.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
